import os
import time
os.system("cls")
print ("#===========================================================================#")
print ("#         █████╗ ██╗  ██╗████████╗██╗██╗   ██╗ █████╗ ███████╗██╗           #")
print ("#        ██╔══██╗██║ ██╔╝╚══██╔══╝██║██║   ██║██╔══██╗██╔════╝██║           #")
print ("#        ███████║█████╔╝    ██║   ██║██║   ██║███████║███████╗██║           #")
print ("#        ██╔══██║██╔═██╗    ██║   ██║╚██╗ ██╔╝██╔══██║╚════██║██║           #")
print ("#        ██║  ██║██║  ██╗   ██║   ██║ ╚████╔╝ ██║  ██║███████║██║           #")
print ("#        ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚═╝  ╚═╝╚══════╝╚═╝           #")
print ("#===========================================================================#\n\n")
print ("telnet 103.148.44.54 223")
print ("password : iGiadxMC")
print ("show gpon onu uncfg")
print ("sho gpon onu state gpon")
print ("-----------------------------------------------------------------------------------------")
print ("-----------------------------------------------------------------------------------------")
sn      = input ("                              SN          : ")
port    = input ("                              Port        : ") 
onu     = input ("                              onu         : ")
nama    = input ("                              Nama        : ")
cid     = input ("                              ID          : ") 

os.system("cls")

print ("\n\n\n\n")  

print ("conf t") 
print ("interface gpon-olt_{}".format(port)) 
print ("  onu {} type ZTEG-F660 sn ".format(onu,sn)) 
print ("!") 
print ("interface gpon-onu_{}:{}".format(port,onu))
print ("  description  {}-{}".format(nama,cid)) 
print ("  tcont 1 name internet profile pppoe")
print ("  tcont 2 name iptv profile iptv")
print ("  gemport 1 name internet tcont 1") 
print ("  gemport 2 name iptv tcont 2")
print ("  service-port 1 vport 1 user-vlan 1541 vlan 1541 ") 
print ("  service-port 1 description internet-pppoe")
print ("  service-port 2 vport 2 user-vlan 1667 vlan 1667 ") 
print ("  service-port 2 description iptv")
print ("!")
print ("")
print ("igmp mvlan 1667 receive-port gpon-onu_{}:{} vport 2".format(port,onu))
print ("pon-onu-mng gpon-onu_{}:{}".format(port,onu))
print ("  service HSI gemport 1 vlan 1541") 
print ("  service IPTV gemport 2 vlan 1667")
print ("  wan-ip 1 mode pppoe username {} password 123456 vlan-profile HSI host 1".format(cid))
print ("  wan-ip 1 ping-response enable traceroute-response enable")
print ("  vlan port eth_0/4 mode tag vlan 1667")
print ("  dhcp-ip ethuni eth_0/4 from-internet")
print ("  mvlan 1667")
print ("  security-mgmt 212 state enable mode forward protocol web ")
print ("  wan 1 ethuni 1,2,3 ssid 1 service internet host 1")
print ("!\n\n\n") 
print ("exit")
print ("wr")

