import os
import time
os.system("cls")
print ("#===========================================================================#")
print ("#         █████╗ ██╗  ██╗████████╗██╗██╗   ██╗ █████╗ ███████╗██╗           #")
print ("#        ██╔══██╗██║ ██╔╝╚══██╔══╝██║██║   ██║██╔══██╗██╔════╝██║           #")
print ("#        ███████║█████╔╝    ██║   ██║██║   ██║███████║███████╗██║           #")
print ("#        ██╔══██║██╔═██╗    ██║   ██║╚██╗ ██╔╝██╔══██║╚════██║██║           #")
print ("#        ██║  ██║██║  ██╗   ██║   ██║ ╚████╔╝ ██║  ██║███████║██║           #")
print ("#        ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚═╝  ╚═╝╚══════╝╚═╝           #")
print ("#===========================================================================#\n\n")

print ("telnet 103.148.44.194 2323")
print ("Passwod : MpTOmpLA")
print ("show gpon onu uncfg")
print ("sho gpon onu state gpon")
print ("-----------------------------------------------------------------------------------------")
print ("-----------------------------------------------------------------------------------------")
sn      = input ("                              SN          : ")
port    = input ("                              Port        : ") 
onu     = input ("                              onu         : ")
nama    = input ("                              Nama        : ")
cid     = input ("                              ID          : ") 

os.system("cls")

print ("\n\n\n\n")

print ("conf t")
print ("interface gpon-olt_{}".format(port))
print ("  onu {} type ALL-ONT sn {}".format(onu,sn))
print ("!")
print ("interface gpon-onu_{}:{}".format(port,onu))
print ("  description  {}-{}".format(nama,cid))
print ("  tcont 1 profile internet")
print ("  tcont 2 profile iptv")
print ("  gemport 1 name internet unicast tcont 1 dir both")
print ("  gemport 2 name iptv unicast tcont 2 dir both")
print ("  switchport mode hybrid vport 1")
print ("  switchport mode hybrid vport 2") 
print ("  service-port 1 vport 1 user-vlan 88 vlan 88")
print ("  service-port 2 vport 2 user-vlan 78 vlan 78")
print ("!")
print ("pon-onu-mng gpon-onu_{}:{}".format(port,onu))
print ("  service internet gemport 1 vlan 88")
print ("  service iptv gemport 2 vlan 78")
print ("  security-mng 1 state enable mode permit protocol web")
print ("  wan-ip 1 mode pppoe username F663NV3a-mng password 123456 vlan-profile Net.Jambi host 1")
print ("!")
print ("igmp mvlan 78 receive-port gpon-onu_{}:{} vport 2".format(port,onu))
print ("!\n\n\n\n")
print ("exit")
print ("write")