import os
import time
os.system("cls")
print ("#===========================================================================#")
print ("#         █████╗ ██╗  ██╗████████╗██╗██╗   ██╗ █████╗ ███████╗██╗           #")
print ("#        ██╔══██╗██║ ██╔╝╚══██╔══╝██║██║   ██║██╔══██╗██╔════╝██║           #")
print ("#        ███████║█████╔╝    ██║   ██║██║   ██║███████║███████╗██║           #")
print ("#        ██╔══██║██╔═██╗    ██║   ██║╚██╗ ██╔╝██╔══██║╚════██║██║           #")
print ("#        ██║  ██║██║  ██╗   ██║   ██║ ╚████╔╝ ██║  ██║███████║██║           #")
print ("#        ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚═╝  ╚═╝╚══════╝╚═╝           #")
print ("#===========================================================================#\n\n")
print ("ssh -oHostKeyAlgorithms=+ssh-dss zte@10.16.100.18")
print ("password : Xx3Bippz")
print ("show gpon onu uncfg")
print ("sho gpon onu state gpon")
print ("-----------------------------------------------------------------------------------------")
print ("-----------------------------------------------------------------------------------------")
sn      = input ("                              SN          : ")
port    = input ("                              Port        : ") 
onu     = input ("                              onu         : ")
nama    = input ("                              Nama        : ")
cid     = input ("                              ID          : ") 

os.system("cls")

print ("\n\n\n\n") 


print ("conf t")
print ("interface gpon-olt_{}".format(port))
print ("  onu {} type ZTE-F660 sn {}".format(onu,sn))
print ("!")
print ("interface gpon-onu_{}:{}".format(port,onu))
print ("  description *{}-{}*".format(nama,cid))
print ("  tcont 1 name internet profile 10MB")
print ("  tcont 2 name IPTV profile 20MB")
print ("  gemport 1 name internet tcont 1")
print ("  gemport 2 name IPTV tcont 2")
print ("  service-port 1 vport 1 user-vlan 61 vlan 61")
print ("  service-port 2 vport 2 user-vlan 666 vlan 666")
print ("!")
print ("pon-onu-mng gpon-onu_{}:{}".format(port,onu))
print ("  service internet gemport 1 vlan 61")
print ("  service iptv gemport 2 vlan 666")
print ("  wan-ip 1 mode pppoe username  {} password 123456 vlan-profile Client host 1".format(cid))
print ("  vlan port eth_0/4 mode tag vlan 666")
print ("  dhcp-ip ethuni eth_0/4 from-internet")
print ("  security-mgmt 212 state enable mode forward protocol web")
print ("!")
print ("igmp mvlan 666 receive-port gpon-onu_{}:{} vport 2".format(port,onu))
print ("!\n\n\n")
print ("exit")
print ("write")
