import os
import time
os.system("cls")
print ("#===========================================================================#")
print ("#         █████╗ ██╗  ██╗████████╗██╗██╗   ██╗ █████╗ ███████╗██╗           #")
print ("#        ██╔══██╗██║ ██╔╝╚══██╔══╝██║██║   ██║██╔══██╗██╔════╝██║           #")
print ("#        ███████║█████╔╝    ██║   ██║██║   ██║███████║███████╗██║           #")
print ("#        ██╔══██║██╔═██╗    ██║   ██║╚██╗ ██╔╝██╔══██║╚════██║██║           #")
print ("#        ██║  ██║██║  ██╗   ██║   ██║ ╚████╔╝ ██║  ██║███████║██║           #")
print ("#        ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚═╝  ╚═╝╚══════╝╚═╝           #")
print ("#===========================================================================#\n\n")
print ("telnet 10.16.100.10")
print ("password : admin")
print ("show gpon onu uncfg")
print ("sho gpon onu state gpon")
print ("-----------------------------------------------------------------------------------------")
print ("-----------------------------------------------------------------------------------------")
sn      = input ("                              SN          : ")
port    = input ("                              Port        : ") 
onu     = input ("                              onu         : ")
nama    = input ("                              Nama        : ")
cid     = input ("                              ID          : ") 

os.system("cls")

print ("\n\n\n\n") 



print ("conf t")
print ("interface gpon-olt_{}".format(port))
print (" onu {} type ZTE-F660 sn {}".format(onu,sn))
print ("!")
print ("")                                             
print ("interface gpon-onu_{}:{}".format(port,onu)  )  
print ("  description  {}-{}".format(nama,cid))
print ("  tcont 1 name Internet profile 1MB")
print ("  tcont 2 name IPTV profile 10MB")
print ("  gemport 1 name internet tcont 1")
print ("  gemport 2 name iptv tcont 2")
print ("  service-port 1 vport 1 user-vlan 313 vlan 313 ")
print ("  service-port 1 description internet")
print ("  service-port 2 vport 2 user-vlan 669 vlan 669 ")
print ("  service-port 2 description iptv")
print ("!")
print ("")
print ("pon-onu-mng gpon-onu_{}:{}".format(port,onu))
print ("  service internet gemport 1 vlan 313")
print ("  service iptv gemport 2 vlan 669")
print ("  wan-ip 1 mode pppoe username {} password 123456 vlan-profile 313.Studio3 host 1".format(cid))
print ("  vlan port eth_0/1 mode tag vlan 313")
print ("  vlan port eth_0/4 mode tag vlan 669")
print ("  vlan port wifi_0/2 mode tag vlan 313")
print ("  dhcp-ip ethuni eth_0/1 from-internet")
print ("  dhcp-ip ethuni eth_0/4 from-internet")
print ("  security-mgmt 212 state enable mode forward protocol web")
print ("  wan 1 ethuni 2,3 ssid 1 service internet host 1")
print ("!")
print ("")
print ("igmp mvlan 669 receive-port gpon-onu_{}:{} vport 2".format(port,onu)) 
print ("!\n\n\n")
print ("exit")
print ("write")