import os
import time
os.system("clear")
print ("#===========================================================================#")
print ("#         █████╗ ██╗  ██╗████████╗██╗██╗   ██╗ █████╗ ███████╗██╗           #")
print ("#        ██╔══██╗██║ ██╔╝╚══██╔══╝██║██║   ██║██╔══██╗██╔════╝██║           #")
print ("#        ███████║█████╔╝    ██║   ██║██║   ██║███████║███████╗██║           #")
print ("#        ██╔══██║██╔═██╗    ██║   ██║╚██╗ ██╔╝██╔══██║╚════██║██║           #")
print ("#        ██║  ██║██║  ██╗   ██║   ██║ ╚████╔╝ ██║  ██║███████║██║           #")
print ("#        ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚═╝  ╚═╝╚══════╝╚═╝           #")
print ("#===========================================================================#\n\n")

print ("telnet 103.148.44.194 2323")
print ("Passwod : MpTOmpLA")
print ("show gpon onu uncfg")
print ("sho gpon onu state gpon")
print ("-----------------------------------------------------------------------------------------")
print ("-----------------------------------------------------------------------------------------")
sn      = input ("                              SN          : ")
port    = input ("                              Port        : ") 
onu     = input ("                              onu         : ")
nama    = input ("                              Nama        : ")
cid     = input ("                              ID          : ") 

os.system("clear")

print ("\n\n\n\n")

print ("conf t")
print ("interface gpon-olt_{}".format(port))
print ("  onu {} type ALL-ONT sn {}".format(onu,sn))
print ("!")
print (" interface gpon-onu_{}:{}".format(port,onu))
print ("  description {}-{}".format(nama,cid))
print ("  tcont 1 name internet profile internet")
print ("  tcont 2 name iptv profile iptv")
print ("  gemport 1 name internet unicast tcont 1 dir both")
print ("  gemport 2 name iptv unicast tcont 2 dir both")
print ("  switchport mode hybrid vport 1")
print ("  switchport mode hybrid vport 2")
print ("  service-port 1 vport 1 user-vlan 87 vlan 87")
print ("  service-port 2 vport 2 user-vlan 78 vlan 78 ")
print ("!")
print ("pon-onu-mng gpon-onu_{}:{}".format(port,onu))
print ("  service iptv gemport 2 vlan 78")
print ("  service internet gemport 1 vlan 87")
print ("  wan-ip 1 mode pppoe username {} password 123456 vlan-profile Net.Jambi87 host 1".format(cid))
print ("  vlan port eth_0/1 mode tag vlan 87")
print ("  vlan port eth_0/3 mode tag vlan 78")
print ("  vlan port eth_0/4 mode tag vlan 78")
print ("  dhcp-ip ethuni eth_0/3 from-internet")
print ("  dhcp-ip ethuni eth_0/4 from-internet")
print ("  security-mng 212 state enable mode permit protocol web ")
print ("!")
print ("")
print ("igmp mvlan 78 receive-port gpon-onu_{}:{} vport 2".format(port,onu))
print ("!\n\n\n")
print ("exit")
print ("write")
