import os
import time
os.system("clear")
print ("#===========================================================================#")
print ("#         █████╗ ██╗  ██╗████████╗██╗██╗   ██╗ █████╗ ███████╗██╗           #")
print ("#        ██╔══██╗██║ ██╔╝╚══██╔══╝██║██║   ██║██╔══██╗██╔════╝██║           #")
print ("#        ███████║█████╔╝    ██║   ██║██║   ██║███████║███████╗██║           #")
print ("#        ██╔══██║██╔═██╗    ██║   ██║╚██╗ ██╔╝██╔══██║╚════██║██║           #")
print ("#        ██║  ██║██║  ██╗   ██║   ██║ ╚████╔╝ ██║  ██║███████║██║           #")
print ("#        ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚═╝  ╚═╝╚══════╝╚═╝           #")
print ("#===========================================================================#\n\n")

print ("telnet 10.255.0.20")
print ("show gpon onu uncfg")
print ("sho gpon onu state gpon")
print ("-----------------------------------------------------------------------------------------")
print ("-----------------------------------------------------------------------------------------")
sn      = input ("                              SN          : ")
port    = input ("                              Port        : ") 
onu     = input ("                              onu         : ")
nama    = input ("                              Nama        : ")
cid     = input ("                              ID          : ") 

os.system("clear")

print ("\n\n\n\n")   
print ("conf t")  
print ("interface gpon-olt_{}".format(port))
print ("  onu {} type ALL-ONT sn {}".format(onu, sn))
print ("!")
print ("interface gpon-onu_{}:{}".format(port, onu))
print ("  description   {}-{}".format(nama,cid))  
print ("  tcont 1 name internet profile internet")  
print ("  tcont 1 gap mode0")
print ("  tcont 2 name iptv profile iptv") 
print ("  gemport 1 tcont 1")
print ("  gemport 2 tcont 2") 
print ("  service-port 1 vport 1 user-vlan 310 vlan 310 ") 
print ("  service-port 2 vport 2 user-vlan 666 vlan 666 ")  
print ("!")
print ("igmp  mvlan 666 receive-port gpon-onu_{}:{}vport 2".format(port,onu))  
print ("!")
print ("pon-onu-mng gpon-onu_{}:{}".format(port,onu)) 
print ("  service internet gemport 1 vlan 310") 
print ("  service iptv gemport 2 vlan 666")
print ("  wan-ip 1 mode pppoe username {} password 123456 vlan-profile User host 1".format(cid))  
print ("  vlan port eth_0/4 mode tag vlan 666")
print ("  dhcp-ip ethuni eth_0/1 from-onu") 
print ("  dhcp-ip ethuni eth_0/4 from-internet")  
print ("  security-mgmt 1 state enable mode forward protocol web") 
print ("!\n\n\n") 
print ("exit")
print ("write") 


