import os
import time
os.system("clear")
print ("#===========================================================================#")
print ("#         █████╗ ██╗  ██╗████████╗██╗██╗   ██╗ █████╗ ███████╗██╗           #")
print ("#        ██╔══██╗██║ ██╔╝╚══██╔══╝██║██║   ██║██╔══██╗██╔════╝██║           #")
print ("#        ███████║█████╔╝    ██║   ██║██║   ██║███████║███████╗██║           #")
print ("#        ██╔══██║██╔═██╗    ██║   ██║╚██╗ ██╔╝██╔══██║╚════██║██║           #")
print ("#        ██║  ██║██║  ██╗   ██║   ██║ ╚████╔╝ ██║  ██║███████║██║           #")
print ("#        ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚═╝  ╚═╝╚══════╝╚═╝           #")
print ("#===========================================================================#\n\n")

print ("telnet 103.148.44.50 223")
print ("show gpon onu uncfg")
print ("sho gpon onu state gpon")
print ("-----------------------------------------------------------------------------------------")
print ("-----------------------------------------------------------------------------------------")
sn      = input ("                              SN          : ")
port    = input ("                              Port        : ") 
onu     = input ("                              onu         : ")
nama    = input ("                              Nama        : ")
cid     = input ("                              ID          : ") 

os.system("clear")

 
print ("\n\n\n\n")
print ("conf t")
print ("interface gpon-olt_{}".format(port))
print ("  onu {} type ZTEG-F660 sn {}".format(onu,sn))
print ("!")
print ("")
print ("interface gpon-onu_{}:{}".format(port,onu)) 
print ("  description 2 $$  *{}-{}*$$".format(nama,cid))
print ("  tcont 1 name HSI profile pppoe")
print ("  tcont 2 name IPTV profile 1MB")
print ("  gemport 1 name HSI tcont 1")
print ("  gemport 2 name IPTV tcont 2") 
print ("  service-port 1 vport 1 user-vlan 1541 vlan 1541")
print ("  service-port 1 description 1541")
print ("  service-port 2 vport 2 user-vlan 505 vlan 505") 
print ("  service-port 2 description 505")
print ("!")
print ("")
print ("pon-onu-mng gpon-onu_{}:{}".format(port,onu))
print ("  service HSI gemport 1 vlan 1541")
print ("  service IPTV gemport 2 vlan 505")
print ("  wan-ip 1 mode pppoe username {} password 123456 vlan-profile HSI host 1".format(cid))
print ("  wan-ip 1 ping-response enable traceroute-response enable")
print ("  vlan port eth_0/4 mode hybrid def-vlan 505")
print ("  dhcp-ip ethuni eth_0/4 from-internet")
print ("  mvlan 505")
print ("  security-mgmt 212 state enable mode forward protocol web")
print ("!")
print ("")
print ("igmp mvlan 505 receive-port gpon-onu_{}:{} vport 2".format(port,onu))
print ("")
print ("")
print ("exit")
print ("wr")
